
modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]] #mandatory
modId="asprussy"
version="${file.jarVersion}"
displayName="ASPRUSSY REAL"
logoFile="logo.png"
credits="Th lack of beans on toast in th US"
authors="Aspr and Aspr"
description='''
From a
'''
[[dependencies.asprandalliums]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.asprandalliums]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.asprandalliums]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.2.0,)"
    ordering = "AFTER"
    side = "BOTH"